### ISSUE TITLE
include country variants for Chinese

### ISSUE THREAD

**Issue by eighthave** [umpirsky/language-list#14]
It is quite common to list the Chinese by country (CN, HK, TW) rather than by written form (Hans, Hant).  It would be nice to include those:

```yaml
  zh_CN: 中文(简体)
  zh_HK: 中文(香港)
  zh_TW: 中文(台灣)
```
